
name: Test-crawler CI

on:
  repository_dispatch:
    types: [test-crawler]

jobs:
  test-crawler:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test-crawler ${{ github.event.client_payload.projectId }}
      uses: apiel/test-crawler/actions/run@master
    - name: Push changes
      uses: apiel/test-crawler/actions/push@master
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
