
name: Test-crawler CI

on:
  repository_dispatch:
    types: [test-crawler]

jobs:
  test-crawler:
    if: github.event.client_payload.os == 'default'
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Enable safari driver
      run: |
        sudo safaridriver --enable
        safaridriver -p 0 &
    - name: testyo1
      run: |
        ls ~
    - name: testyo2
      run: |
        pwd
    - name: testyo2
      run: |
        ls
    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/node_modules/puppeteer-core/.local-chromium
        key: puppeteer-local-chromium
    - name: Run test-crawler ${{ github.event.client_payload.projectId }}
      uses: apiel/test-crawler/actions/crawl@master
    - name: Push changes
      uses: apiel/test-crawler/actions/push@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  test-crawler-windows:
    if: github.event.client_payload.os == 'win'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run test-crawler ${{ github.event.client_payload.projectId }}
      uses: apiel/test-crawler/actions/crawl@master
    - name: Push changes
      uses: apiel/test-crawler/actions/push@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
